Media.xcodeproj/project.pbxproj, Media/Infrastructure/APIEndpoints.swift, Media/Infrastructure/DataTransfer/Endpoint/Endpoint.swift, Media/Infrastructure/DataTransfer/Endpoint/Requestable.swift, Media/Infrastructure/DataTransfer/Network/NetworkConfiguration.swift, Media/Model/API/Category.swift, Media/Model/API/Order.swift, Media/Model/Response/Mock/PixabayResponse.json, Media/Model/Response/PixabayResponse+Mock.swift, Media/Model/Response/PixabayResponse.swift, Media/Presentation/Home/HomeViewController.swift
close #10 
* `PixabayResponse` 디코더블 구조체 작성, 목(mock) 데이터 작성
* 픽사베이 비디오 및 이미지를 가져오는 `pixabay(_:)`, `thumbnail(_:)` APIEndpoints 코드 구현
```swift
static func pixabay(
query: String? = nil,
category: Category? = nil,
order: Order = .popular,
page: Int = 1,
perPage: Int = 3
) -> Endpoint<PixabayResponse>
static func thumbnail(url: URL) -> Endpoint<Data>
```
=> feat: `PixabayResponse` 디코더블 구조체 작성, `pixabay(_:)`, `thumbnail(_:)` APIEndpoints 코드 구현

Media/Presentation/Home/HomeViewController.storyboard, Media/Presentation/Home/HomeViewController.swift
home 스토리보드 table View > collection View로 수정
=> [Fix] home 스토리보드 table View > collection View로 수정

Media/Core/Extensions/UIColor+Extension.swift, Media/Resources/Assets.xcassets/New Folder/Background.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/Contents.json, Media/Resources/Assets.xcassets/New Folder/MainLabel.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/Primary.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/SearchBarBackground.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/SubLabel.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/TagBorder.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/TagSelected.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/TagUnselected.colorset/Contents.json
close #17 
- Primary (포인트)
- Background (배경)
- Tag (선택)
- Tag (비선택)
- Tag Border (태그 테두리)
- SearchBar Background (검색바 배경)
- Main Label 
- Sub Label
=> feat: 색상 에셋 정의 및 UIColor+Extension 추가

Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift, Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents, Media/Model/CoreData/Playlist/PlaylistEntity+CoreDataProperties.swift, Media/Presentation/Home/HomeViewController.swift
close #20 
* `PixabayResponse.mock` 데이터를 활용해 북마크 화면에서 사용할 목(mock) 데이터 엔터티 작성
=> feat: 북마크 관련 Entity에 목 데이터 추가

Media.xcodeproj/project.pbxproj, Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents.rej, Media/Presentation/Onboarding/Cell/OnboardingTegsViewCell.swift, Media/Presentation/Onboarding/OnBoardingOnBoardingViewController.storyboard, Media/Presentation/Onboarding/OnBoardingTagsViewController.storyboard, Media/Presentation/Onboarding/OnBoardingTagsViewController.swift, Media/Presentation/Onboarding/OnboardingImageViewController.swift
=> feat: 온보딩 파일 및 Tags CoreData 생성

Media/Presentation/Home/CategoryCell/CategoryCell.swift, Media/Presentation/Home/HomeViewController.storyboard, Media/Presentation/Home/HomeViewController.swift, Media/Presentation/Home/Video.swift, Media/Presentation/Home/VideoCell/VideoCell.swift, Media/Presentation/Home/VideoCell/VideoCell.xib, Media/Presentation/Home/VideoCell/VideoCellUsing.swift, Media/Presentation/Home/VideoCell/VideoCellViewModel.swift
Home화면 video api연결 및 디자인설정 및 폰트색상변경
아직 터치이벤트 및 추가기능은 미구현
디자인만 구현
=> [Feat] Home 화면 video api연결 및 디자인설정 및 폰트색상변경

Media/Core/Extensions/UIColor+Extension.swift, Media/Resources/Assets.xcassets/New Folder/OnboardingBackground.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/TagUnselected.colorset/Contents.json
close #40 
- Tag (비선택): 색상 변경
- OnboardingBackground: 색상 추가
=> feat: 색상 asset 및 UIColor+Extension 수정

Media/Core/Common/NavigationBar/NavigationBar.swift, Media/Core/Common/NavigationBar/NavigationBar.xib
close #45 
XIB에서 버튼 액션이 안 먹히는 문제 발생 
→ 액션을 코드로 연결하는 방식으로 변경 (`@IBAction` → `@objc private` )
=> fix: 네비바 버튼 액션이 작동하지 않는 문제

Media/Presentation/Base.lproj/Main.storyboard, Media/Presentation/Settings/Cell/SwitchTableViewCell.swift, Media/Presentation/Settings/Cell/SwitchTableViewCell.xib, Media/Presentation/Settings/SettingsTableViewController.swift, Media/Presentation/Settings/SettingsViewController.storyboard, Media/Presentation/Settings/SettingsViewController.swift
close #49 
- 설정 화면 UI 
</br>
</br>
- 탭 바 섞인 거 일부 해결
- 두번째 탭: Settings -> Interests
- 네번째 탭: History -> Settings
=> feat: 설정 화면 UI 구현 

Media/Presentation/Bookmark/BookmarkViewController.swift, Media/Presentation/Bookmark/VideoListViewController.swift, Media/Presentation/Bookmark/View/Cells/HeaderReusableView.xib, Media/Presentation/Bookmark/View/Cells/MediumVideoCell.swift, Media/Presentation/Bookmark/View/Cells/SmallVideoCell.xib
- 재생 목록/플레이리스트 비디오 항목을 보여주는 컬렉션 뷰 셀에서 삭제 버튼 탭하면 alert 창 띄우기
- 플레이리스트 폴더 뷰(SmallVideoView UI 수정)
=> [feat] 재생 목록/플레이리스트 비디오 항목 delete alert

Media/Presentation/Home/HomeViewController.swift
=> [Fix] Home Ellipsis 메뉴버튼 재생목록생성시 토스트 수정 및 재생목록리스트에서 북마크 제외

Media/Application/SceneDelegate.swift, Media/Infrastructure/Storage/UserDefaults/UserDefaultsKeys.swift, Media/Model/Enum/VideoQuality.swift, Media/Presentation/Settings/Cell/SwitchTableViewCell.swift, Media/Presentation/Settings/EditProfileViewController.swift, Media/Presentation/Settings/SettingsTableViewController.swift, Media/Presentation/Settings/SettingsViewController.storyboard, Media/Presentation/Settings/SettingsViewController.swift
close #67 
- 설정 화면
- Name cell -> 이름 변경
- E-mail cell -> 이메일 변경
- Interests cell -> 취향 선택 화면 이동
- Video Quality cell -> 영상 해상도 변경
- Mode cell -> 라이트 / 다크 모드 변경
- Feddback cell -> 메일 보내기 기능
=> feat: 설정 화면 기능 구현 

Media/Core/Extensions/NotificationName+Extension.swift, Media/Model/API/Category.swift, Media/Presentation/Onboarding/OnBoardingTagsViewController.storyboard, Media/Presentation/Onboarding/OnBoardingTagsViewController.swift, Media/Presentation/Onboarding/OnboardingImageViewController.swift, Media/Presentation/SelectedCategory/SelectedTagsViewController.swift
최소 선택 카테고리 개수 3개로 수정, selectedTagsView에서 선택 된 셀 개수 인식문제 해결, Category 오타수정 
Notification.Name extension파일 추가
=> Selected tags view

Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift, Media/Presentation/Bookmark/BookmarkViewController.swift, Media/Presentation/Bookmark/Section/VideoListSection.swift, Media/Presentation/Bookmark/VideoListViewController.swift, Media/Presentation/Bookmark/View/Cells/MediumVideoCell.swift
close #76 
* 홈에서 비디오 클릭 시, 재생 기록에 데이터가 제대로 삽입이 안되는 문제 수정, 데이터가 삽입되면 컬렉션 뷰가 제대로 갱신되지 않는 문제 수정
=> fix: 재생 목록 및 재생 기록에 비디오 데이터 추가 (스냅샷 충돌) 문제 수정

Media/Application/SceneDelegate.swift
=> fix: 다크모드 데이터 저장 복구

Media/Application/SceneDelegate.swift
=> fix: 다크모드와 온보딩 데이터 저장 병합

Media/Presentation/Home/HomeViewController.swift
=> [Fix] 필터링 안되던 오류 수정완료

Media/Presentation/Base.lproj/Main.storyboard, Media/Presentation/Settings/Cell/SwitchTableViewCell.xib, Media/Presentation/Settings/EditProfileViewController.swift, Media/Presentation/Settings/SettingsTableViewController.swift, Media/Presentation/Settings/SettingsViewController.storyboard
close #117 
- 테이블 뷰 디자인 수정
- 이름 / 이메일 텍스트필드에서 수정 후 `done` 버튼 클릭하면 키보드 내려가도록 수정
- 수정 전
- 수정 후
- 키보드 로직 추가
=> feat: 설정 화면 -  UI 개선 및 키보드 처리 로직 추가

Media/Presentation/Home/CategoryCell/CategoryCell.swift, Media/Presentation/Home/HomeViewController.swift, Media/Presentation/Home/VideoCell/VideoCell.swift, Media/Presentation/Home/VideoCell/VideoCell.xib
close #123
close #139
close #149
close #151 
=> [Fix] 홈에서 재생목록 비디오 중복처리 완료, 태그/시간 라벨 다크모드대응, 홈화면 카테고리 테두리변경, 카테고리갱신

Media/Application/AppDelegate.swift, Media/Infrastructure/Storage/CoreData/CoreDataService+Defaults.swift, Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift, Media/Infrastructure/Storage/UserDefaults/UserDefaultsKeys.swift, Media/Infrastructure/VideoPlayer/PIPVideoPlayerViewController.swift, Media/Infrastructure/VideoPlayer/VideoPlayerService.swift, Media/Presentation/SelectedCategory/SelectedTagsViewController.swift
close #150 
close #155 
close #158 
* TagSelectedViewController에서 `Confirm` 버튼 클릭 시, 전체 데이터가 삭제되는 코드(deleteAll) 삭제
> 광호님 조금있다 확인 부탁드립니다!
=> fix: `TagsSelectedViewController`에서 `Confirm` 버튼 클릭 시, 전체 데이터가 삭제되는 코드 삭제, 북마크 화면 또는 홈 화면 진입 시 크래시나는 오류 수정

Media/Presentation/Home/HomeViewController.swift
=> [Fix] 홈화면에서 비디오 재생이 안되던 현상 수정

Media/Core/Protocols/VideoPlayable.swift, Media/Presentation/Home/HomeViewController.swift
=> [Fix] popover 화면전환시 제거, 비디오재생이후 리로드 삭제

Media/Presentation/Home/HomeViewController.storyboard, Media/Presentation/Search/SearchResultViewController.swift
=> fix: homeVC 제약추가

Media/Presentation/Home/HomeViewController.storyboard, Media/Presentation/Home/HomeViewController.swift
=> [Feat] Home 화면에서 네트워크 연결안될경우 이미지 추가

Media/Model/API/Category.swift, Media/Presentation/Onboarding/OnBoardingTagsViewController.swift, Media/Presentation/SelectedCategory/Cell/SelectedTagsViewControllerCell.swift, Media/Presentation/SelectedCategory/SelectedTagsViewController.storyboard, Media/Presentation/SelectedCategory/SelectedTagsViewController.swift
=> Tag v iew UI

Media/Presentation/Home/HomeViewController.swift, Media/Presentation/Home/VideoCell/VideoCell.swift
=> [Fix] 프로필안나오는 오류 해결

Media/Core/Extensions/UIColor+Extension.swift, Media/Presentation/SelectedCategory/SelectedTagsViewController.storyboard, Media/Presentation/SelectedCategory/SelectedTagsViewController.swift, Media/Resources/Assets.xcassets/New Folder/CategorySelected.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/CategoryUnselected.colorset/Contents.json, Media/Resources/Assets.xcassets/New Folder/CategoryUnselectedBackground.colorset/Contents.json
- 커스텀 컬러 추가
- `categorySelectedColor` / `categoryUnselectedColor` / `categoryUnselectedBackgroundColor`
- 버튼 아이콘 크기 / 색상 수정
- 버튼 라벨 폰트 / 색상 수정
=> fix: 취향 선택 버튼 디자인 수정

Media/Presentation/Home/HomeViewController.swift, Media/Presentation/Search/SearchResultViewController.swift
=> fix: 코어 데이터에 저장하면 selectedVideo = nil로 변경

Media/Presentation/Bookmark/Section/BookmarkSection.swift
아이패드 환경에서
북마크의 재생기록 셀의 너비를 약간 더 늘렸습니다~ 
=> fix: 아이패드 환경에서 북마크의 재생 기록(Playback) 셀의 너비 수정

Media/Presentation/Search/SearchFilterViewController.storyboard, Media/Presentation/Search/SearchFilterViewController.swift, Media/Presentation/Settings/SettingsViewController.storyboard
=> Hotfix: filterView 하단의 버튼 stackView bottom constraint 조정

Media/Presentation/Bookmark/VideoListViewController.swift, Media/Presentation/Onboarding/OnBoardingOnBoardingViewController.storyboard
=> fix: 온보딩 제목 및 부제목의 제약 조건 변경
